spring.application.name=api_etudiant
server.port=8080

# Configuration PostgreSQL (pour Docker)
spring.datasource.url=jdbc:postgresql://db:5432/etudiantdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect