services:
  db:
    image: postgres:15
    container_name: etudiant_db
    environment:
      POSTGRES_DB: etudiantdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build: ./api-spring-boot/api_etudiant
    container_name: etudiant_api
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/etudiantdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
